RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_Wife::
	msgbox RustboroCity_House2_Text_DuskStone, MSGBOX_NPC
	end

RustboroCity_House2_Text_DuskStone:
	.string "There's a DUSK STONE in the corner\n"
	.string "if you want it. It only evolves\p"
	.string "MURKROW and MISDREAVUS, so it was\n"
	.string "no use to any of us.$"

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "The GYM hasn't been the same ever since\n"
	.string "TYLER left. Now there's two rascals\p"
	.string "competing for the spot! If it were\n"
	.string "up to me, I'd kick them both out!$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "TYLER, the old GYM LEADER, was\n"
	.string "the coolest. I wonder where he\p"
	.string "ended up now that he left!$"

